### ISSUE TITLE
No Recipes available

### ISSUE THREAD

**Issue by chavhector** [plastikos/yocto_gumstix_dspbridge#2]
Hello,

I am following your instructions to create the distribution with DSP support and I am stuck with these 2 errors:
$Yocto/waterstorm_sandbox/poky/meta-gumstix-dspbridge/recipes-devtools/gcc/gcc-cross-initial_4.7.bbappend
$Yocto/waterstorm_sandbox/poky/meta-gumstix-dspbridge/recipes-devtools/binutils/binutils-cross_2.23.1.bbappend

what am I missing?

Thank you.

**Comment by plastikos** [comment]
Unfortunately I abandoned development on this.  I'm disappointed by TI's support of the product, the maintenance of the packages and the lack of completeness of dspbridge and other CPU <=> DSP connection designs for the TI Arm CPUs.

I'm sorry.
